export const questions = [
  {
    id: 1,
    question_text: "ما هي عاصمة المملكة العربية السعودية؟",
    option_1: "جدة",
    option_2: "الرياض",
    option_3: "الدمام",
    option_4: "مكة المكرمة",
    correct_answer: 2,
    category: "Travel",
    difficulty: "easy",
  },
  {
    id: 2,
    question_text: "من هو مخترع المصباح الكهربائي؟",
    option_1: "ألكسندر جراهام بيل",
    option_2: "إسحاق نيوتن",
    option_3: "توماس إديسون",
    option_4: "ألبرت أينشتاين",
    correct_answer: 3,
    category: "Technology",
    difficulty: "easy",
  },
  {
    id: 3,
    question_text: "كم عدد القارات في العالم؟",
    option_1: "5",
    option_2: "6",
    option_3: "7",
    option_4: "8",
    correct_answer: 3,
    category: "Travel",
    difficulty: "easy",
  },
  {
    id: 4,
    question_text: "ما هو أطول نهر في العالم؟",
    option_1: "نهر الأمازون",
    option_2: "نهر النيل",
    option_3: "نهر اليانغتسي",
    option_4: "نهر المسيسيبي",
    correct_answer: 2,
    category: "Travel",
    difficulty: "medium",
  },
  {
    id: 5,
    question_text: "في أي عام بدأت الحرب العالمية الثانية؟",
    option_1: "1914",
    option_2: "1939",
    option_3: "1945",
    option_4: "1923",
    correct_answer: 2,
    category: "History",
    difficulty: "hard",
  },
];
